### ISSUE TITLE
Laravel default locale is not in the supportedLocales array

### ISSUE THREAD

**Issue by Sebi94nbg** [mcamara/laravel-localization#497]
PHP 7.1.7
Laravel v5.5.14
Laravel Localization v1.3.2

I've just done these steps (in exact this sequence):

Install laravel-localization with composer:

`composer require mcamara/laravel-localization`

Published vendor files:

`php artisan vendor:publish --provider="Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider"`

Only enabled `de` and `en` in the published config file:

`config/laravellocalization.php`

And updated these config values in `config/app.php`:

```
'locale' => 'de',
'fallback_locale' => 'de',
```

And I've added it to `providers` and `aliases` in the `config/app.php`.

Is there anything else, what I need to do or did I just already something wrong? Because I'm getting now this error message all the time, when I try to open a language prefix-grouped route:

> Laravel default locale is not in the supportedLocales array.

After the configuration and installation, Laravel only returns a HTTP 500 error:
```
[2017-10-12 21:13:33] local.ERROR: Laravel default locale is not in the supportedLocales array. {"exception":"[object] (Mcamara\\LaravelLocalization\\Exceptions\\UnsupportedLocaleException(code: 0): Laravel default locale is not in the supportedLocales array. at /home/vagrant/dev/laravel/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php:129)
[stacktrace]
#0 /home/vagrant/dev/laravel/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalizationServiceProvider.php(52): Mcamara\\LaravelLocalization\\LaravelLocalization->__construct()
#1 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Mcamara\\LaravelLocalization\\LaravelLocalizationServiceProvider->Mcamara\\LaravelLocalization\\{closure}(Object(Illuminate\\Foundation\\Application), Array
)
#2 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build(Object(Closure))
#3 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('Mcamara\\\\Laravel...', Array)
#4 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\\Container\\Container->make('Mcamara\\\\Laravel...', Array)
#5 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(1195): Illuminate\\Foundation\\Application->make('Mcamara\\\\Laravel...')
#6 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(159): Illuminate\\Container\\Container->offsetGet('laravellocaliza...')
#7 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(128): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('laravellocaliza...')
#8 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#9 /home/vagrant/dev/laravel/routes/web.php(167): Illuminate\\Support\\Facades\\Facade::__callStatic('setLocale', Array)
#10 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(380): require('/home/vagrant/4...')
#11 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(336): Illuminate\\Routing\\Router->loadRoutes('/home/vagrant/4...')
#12 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(105): Illuminate\\Routing\\Router->group(Array, '/home/vagrant/4...')
#13 /home/vagrant/dev/laravel/app/Providers/RouteServiceProvider.php(56): Illuminate\\Routing\\RouteRegistrar->group('/home/vagrant/4...')
#14 /home/vagrant/dev/laravel/app/Providers/RouteServiceProvider.php(40): App\\Providers\\RouteServiceProvider->mapWebRoutes()
#15 [internal function]: App\\Providers\\RouteServiceProvider->map()
#16 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#17 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(74): Illuminate\\Container\\Container->call(Array)
#21 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(33): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->loadRoutes()
#22 /home/vagrant/dev/laravel/app/Providers/RouteServiceProvider.php(28): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->boot()
#23 [internal function]: App\\Providers\\RouteServiceProvider->boot()
#24 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#26 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->call(Array)
#29 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(764): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\RouteServiceProvider))
#30 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\RouteServiceProvider), 18)
#31 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(765): array_walk(Array, Object(Closure))
#32 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#33 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#34 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#35 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#36 /home/vagrant/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#37 /home/vagrant/dev/laravel/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#38 {main}
"}
```

**Comment by Sebi94nbg** [comment]
When I `var_dump($supportedLocales);` in the `__construct()` function of `vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php`, I still get the vendor supported locales.

So it looks like, as it would not use my `config/laravellocalization.php`. But why?

**Comment by Sebi94nbg** [comment]
Ok, I was able to fix this problem. I'm not sure, if I did just something wrong or if there is an issue in this package.

The [configuration cache of Laravel](https://laravel.com/docs/5.5/configuration#configuration-caching) did just cache the vendor published config settings.

Unfortunately, due of this `Laravel default locale is not in the supportedLocales array.` error, I was unable to rebuild the cache:

```
$ php artisan config:clear

  [Mcamara\LaravelLocalization\Exceptions\UnsupportedLocaleException]
  Laravel default locale is not in the supportedLocales array.
```

As workaround, I've simply [commented the related code](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L128-L130) in order to disable it quickly:

```
    /**
     * Creates new instance.
     *
     * @throws UnsupportedLocaleException
     */
    public function __construct()
    {
        $this->app = app();

        $this->configRepository = $this->app['config'];
        $this->view = $this->app['view'];
        $this->translator = $this->app['translator'];
        $this->router = $this->app['router'];
        $this->request = $this->app['request'];
        $this->url = $this->app['url'];

        // set default locale
        $this->defaultLocale = $this->configRepository->get('app.locale');
        $supportedLocales = $this->getSupportedLocales();

        /*if (empty($supportedLocales[$this->defaultLocale])) {
            throw new UnsupportedLocaleException('Laravel default locale is not in the supportedLocales array.');
        }*/
    }
```

After this, I were able to rebuild the cache:

```
$ php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
```

After `config:cache` I've uncommented the above mentioned code again like it was before.

Since this it's using the correct `supportedLocales` and I also don't get any error anymore.

**Comment by Sebi94nbg** [comment]
Sorry @mcamara, but I left this issue open, because I had this issue regarding caching and this exception.

Did I something wrong while setting up this package? I think, that the code needs to be improved.

**Comment by czagalaca** [comment]
Anotherway in a new project: 
First to set the  vendor\mcamara\laravel-localization\src\config\config.php and after publish!

**Comment by AymanElshehawy** [comment]
I had the same error, but for me it was a silly mistake: I added the some code on route.php

` // app/Http/routes.php

Route::group(['prefix' => LaravelLocalization::setLocale()], function()`
Before run the publish command:

php artisan vendor:publish --provider="Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider"

I obviously needed to first publish the plugin, config the supportedLocales, and then add any code that I want.

**Comment by edurodriguesdias** [comment]
I had the same error, but my mistake was a locale seted on config/app.php file that was not equal the locale alias from laravellocalization.php file. 

For brazilians programmers, change the index 'pt-BR' for 'pt-br' on the line 147 of laravellocalization.php file or check your locale in config/app.php and change it.

**Comment by iwasherefirst2** [comment]
@Sebi94nbg is this issue still present?
